name: Game of Life CD pipeline
on:
  push:
    branches: [main]

jobs:
  deploy_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: scp -r /home/runner/work/life/life/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/owen/life
